language: ruby
rvm:
- 2.3.0
- 2.4.0
- 2.5.1
bundler_args: --jobs=2
script:
script:
  - cd gema
  - gem update --system '2.7.9'
  - bundle install
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
